// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBD0TJc67vf9mZb_VwX6RWQ-qMrpWNDjo4',
    appId: '1:873056120753:web:bcc92d9c0603e885c1d790',
    messagingSenderId: '873056120753',
    projectId: 'walletflow-app-f4069',
    authDomain: 'walletflow-app-f4069.firebaseapp.com',
    storageBucket: 'walletflow-app-f4069.firebasestorage.app',
    measurementId: 'G-J4MD3S10NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB__DW00pEbSRLYg_ZxgO9-VaAQQYIOVoM',
    appId: '1:873056120753:android:831224665a7538e0c1d790',
    messagingSenderId: '873056120753',
    projectId: 'walletflow-app-f4069',
    storageBucket: 'walletflow-app-f4069.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB__DW00pEbSRLYg_ZxgO9-VaAQQYIOVoM',
    appId: '1:873056120753:android:831224665a7538e0c1d790',
    messagingSenderId: '873056120753',
    projectId: 'walletflow-app-f4069',
    storageBucket: 'walletflow-app-f4069.firebasestorage.app',
    iosBundleId: 'com.walletflow.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB__DW00pEbSRLYg_ZxgO9-VaAQQYIOVoM',
    appId: '1:873056120753:android:831224665a7538e0c1d790',
    messagingSenderId: '873056120753',
    projectId: 'walletflow-app-f4069',
    storageBucket: 'walletflow-app-f4069.firebasestorage.app',
    iosBundleId: 'com.walletflow.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB__DW00pEbSRLYg_ZxgO9-VaAQQYIOVoM',
    appId: '1:873056120753:android:831224665a7538e0c1d790',
    messagingSenderId: '873056120753',
    projectId: 'walletflow-app-f4069',
    storageBucket: 'walletflow-app-f4069.firebasestorage.app',
  );
}