// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'TU_WEB_API_KEY_AQUI',
    appId: 'TU_WEB_APP_ID_AQUI',
    messagingSenderId: '873056120753',
    projectId: 'walletflow-app-f4069',
    authDomain: 'walletflow-app-f4069.firebaseapp.com',
    storageBucket: 'walletflow-app-f4069.firebasestorage.app',
    measurementId: 'TU_MEASUREMENT_ID_AQUI',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB__DW00pEbSRLYg_ZxgO9-VaAQQYIOVoM',
    appId: '1:873056120753:android:831224665a7538e0c1d790',
    messagingSenderId: '873056120753',
    projectId: 'walletflow-app-f4069',
    storageBucket: 'walletflow-app-f4069.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'TU_IOS_API_KEY_AQUI',
    appId: 'TU_IOS_APP_ID_AQUI',
    messagingSenderId: '873056120753',
    projectId: 'walletflow-app-f4069',
    storageBucket: 'walletflow-app-f4069.firebasestorage.app',
    iosBundleId: 'com.walletflow.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'TU_MACOS_API_KEY_AQUI',
    appId: 'TU_MACOS_APP_ID_AQUI',
    messagingSenderId: '873056120753',
    projectId: 'walletflow-app-f4069',
    storageBucket: 'walletflow-app-f4069.firebasestorage.app',
    iosBundleId: 'com.walletflow.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'TU_WINDOWS_API_KEY_AQUI',
    appId: 'TU_WINDOWS_APP_ID_AQUI',
    messagingSenderId: '873056120753',
    projectId: 'walletflow-app-f4069',
    storageBucket: 'walletflow-app-f4069.firebasestorage.app',
  );
}